### ISSUE TITLE
opsgenie plugin does not work with sensu-ruby-runtime_0.0.8_ruby-2.4.4_alpine_linux_amd64.tar.gz with sensu go

### ISSUE THREAD

**Issue by daswars** [sensu-plugins/sensu-plugins-opsgenie#63]
Hi i test the opsgenie plugin does not work with sensu-ruby-runtime_0.0.8_ruby-2.4.4_alpine_linux_amd64.tar.gz with sensu go

Here my errors:
```
/var/cache/sensu/sensu-backend # handler-opsgenie.rb --help
/var/cache/sensu/sensu-backend/5e8ec99e5a13e07891c6426e8be9293036f5fe1075dbc3634ddf670d5e4032295373c11f8b25e8c3af8787c8db9094aba45197645e66571fc9dfd921f3930dcf/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- sensu-handler (LoadError)
	from /var/cache/sensu/sensu-backend/5e8ec99e5a13e07891c6426e8be9293036f5fe1075dbc3634ddf670d5e4032295373c11f8b25e8c3af8787c8db9094aba45197645e66571fc9dfd921f3930dcf/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/cache/sensu/sensu-backend/b3fd627689526b1947a8d12abf81f6f73be5d69eea14724282b345603352a3f6407fb9b8bdfbcf343f5ee59053c110ef29b9be297033a553bc530ab9cca636d2/bin/handler-opsgenie.rb:7:in `<main>'
```

```
---
type: Handler
api_version: core/v2
metadata:
  annotations:
    customerKey: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx
  name: opsgenie
  namespace: default
spec:
  command: handler-opsgenie.rb --map-go-event-into-ruby
  env_vars:
  - SENSU_MAP_GO_EVENT_INTO_RUBY=1
  filters: null
  handlers: null
  runtime_assets:
  - sensu-ruby-runtime-alpine
  - sensu-opsgenie-handler
  timeout: 0
  type: pipe
```
